### ISSUE TITLE
Specify license?

### ISSUE THREAD

**Issue by frewsxcv** [huonw/crates.io-graph#4]
I'd like to reuse some of your code for a personal project. Considering you don't specify a license anywhere, I am unable to use it (and subsequently attribute it to you).

**Comment by huonw** [comment]
Oops!

Hey @brookst and @nathantypanski, you've contributed to this repo; is it OK if I license this as MIT & Apache-2.0? (I guess this question applies to you too, @frewsxcv.)

**Comment by frewsxcv** [comment]
I consent to re-licensing this as MIT & Apache-2.0.

**Comment by nathantypanski** [comment]
I consent to re-licensing this as MIT & Apache-2.0.

**Comment by brookst** [comment]
I consent to re-licensing this as MIT & Apache-2.0.

:+1:

**Comment by huonw** [comment]
Yay, thanks everyone!

**Comment by frewsxcv** [comment]
In case anyone was wondering what I did with the DOT + crates.io code from this repository:

https://github.com/frewsxcv/crate-deps

in particular

https://github.com/frewsxcv/rust-crates-index

**Comment by huonw** [comment]
Very cool!
